### ISSUE TITLE
cannot convert from 'Microsoft.AspNetCore.Http.IHttpContextAccessor' to 'Microsoft.Extensions.ObjectPool.ObjectPoolProvider'

### ISSUE THREAD

**Issue by miguellira** [OmniSharp/omnisharp-roslyn#497]
While attempting to build OmniSharp from source in order to get it working with Visual Studio Code against the most recent dotnet CLI (`1.0.0-beta-002202`) I ran into the following error:
```console
/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/src/OmniSharp.Stdio/StdioServer.cs(34,58): error CS1503: Argument 1: cannot convert from 'Microsoft.AspNetCore.Http.IHttpContextAccessor' to 'Microsoft.Extensions.ObjectPool.ObjectPoolProvider'
```
Is there a more "stable" CLI build that works with OmniSharp AND the `netstandard1.5`?

### Steps to reproduce
git clone https://github.com/OmniSharp/omnisharp-roslyn.git
git checkout dev
./build.sh

### Expected behavior
Successful build and proper artifacts
### Actual behavior
Error when executing `TestCore` during build
```console
Executing task: TestCore
Project OmniSharp.Bootstrap (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project OmniSharp.Bootstrap.Tests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
xUnit.net DNX Runner (64-bit osx.10.11-x64)
  Discovering: OmniSharp.Bootstrap.Tests
  Discovered:  OmniSharp.Bootstrap.Tests
  Starting:    OmniSharp.Bootstrap.Tests
  Finished:    OmniSharp.Bootstrap.Tests
=== TEST EXECUTION SUMMARY ===
   OmniSharp.Bootstrap.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 0.291s
Project OmniSharp.Abstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project OmniSharp.Roslyn (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project OmniSharp.Nuget (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Compiling OmniSharp.Stdio for .NETStandard,Version=v1.3
/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/.dotnet/dotnet compile-csc @/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/src/OmniSharp.Stdio/obj/Debug/netstandard1.3/dotnet-compile.rsp returned Exit Code 1
/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/src/OmniSharp.Stdio/project.json(10,37): warning NU1007: Dependency specified was Microsoft.AspNetCore.Hosting >= 1.0.0-rc2-20143 but ended up with Microsoft.AspNetCore.Hosting 1.0.0-rc2-20410.
/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/src/OmniSharp.Stdio/project.json(11,43): warning NU1007: Dependency specified was Microsoft.AspNetCore.Http.Features >= 1.0.0-rc2-20143 but ended up with Microsoft.AspNetCore.Http.Features 1.0.0-rc2-20410.
/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/src/OmniSharp.Stdio/project.json(12,24): warning NU1012: Dependency conflict. Microsoft.Extensions.Configuration.Json 1.0.0-rc2-20410 expected Newtonsoft.Json >= 8.0.3 but got 8.0.2
/Users/miguellira/Documents/Github/OmniSharp/omnisharp-roslyn/src/OmniSharp.Stdio/StdioServer.cs(34,58): error CS1503: Argument 1: cannot convert from 'Microsoft.AspNetCore.Http.IHttpContextAccessor' to 'Microsoft.Extensions.ObjectPool.ObjectPoolProvider'

Compilation failed.
    3 Warning(s)
    1 Error(s)

Time elapsed 00:00:04.8958990
An error occured when executing task 'TestCore'.
Error: Test failed OmniSharp.Roslyn.CSharp.Tests / netcoreapp1.0
```
### Enviornment info
```console
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by david-driscoll** [comment]
I was having success just last night with

```
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by miguellira** [comment]
@david-driscoll I wish I had your machine :stuck_out_tongue_winking_eye: 

I just gave it a shot on my Windows 10 VM and I'm getting the same error:

<img width="1263" alt="screen shot 2016-04-04 at 2 28 34 pm" src="https://cloud.githubusercontent.com/assets/1449255/14258701/982693a0-fa71-11e5-8855-92f666698bea.png">

BTW, the restores of the various projects produce a large number of "package downgrade", presumably because the latest CLI requires different bits. Do you see that as well? Anything I should clear out or reset?

**Comment by miguellira** [comment]
Looks like @DustinCampbell @troydai and @hal-ler are all working towards a working build that targets the latest CLI and this issue should go away soon. Until then, if you **MUST** have a working envionrment now: 

**Windows 10**
Got it working on by going to the [AppVeyor history](https://ci.appveyor.com/project/david-driscoll/omnisharp-roslyn/history), pulling down a working build, and configuring VS Code accordingly.

**OS X**
The following [branch](https://github.com/OmniSharp/omnisharp-roslyn/tree/troy/fix.deps) - which is still in flux - ) worked for me.

**Comment by DustinCampbell** [comment]
We're almost there. :smile:

**Comment by troydai** [comment]
@miguellira fixes have been merged to `dev`. Thanks for reporting this issue.

**Comment by miguellira** [comment]
@troydai :clap: Building `dev` as I type. Thanks for fixing this.
